/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author mallan
 */
public class AdminInloggning extends javax.swing.JFrame {

    private InfDB idb;
    private boolean lyckadInloggning;


    /**
     * Konstruktor för AdminInloggning
     */
    public AdminInloggning(InfDB db) {
        idb = db;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblLoggain = new javax.swing.JLabel();
        btnLoggain = new javax.swing.JButton();
        txtEpost = new javax.swing.JTextField();
        txtLosenord = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEpost.setFont(new java.awt.Font("Beirut", 0, 12)); // NOI18N
        lblEpost.setText("Epost:");

        lblLosenord.setFont(new java.awt.Font("Beirut", 0, 12)); // NOI18N
        lblLosenord.setText("Lösenord:");

        lblLoggain.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        lblLoggain.setText("Logga in Admin");

        btnLoggain.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnLoggain.setText("Logga in");
        btnLoggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggainActionPerformed(evt);
            }
        });

        txtEpost.setColumns(4);
        txtEpost.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N

        txtLosenord.setColumns(4);
        txtLosenord.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLoggain)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEpost)
                                .addComponent(lblLosenord))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(btnLoggain))
                    .addContainerGap(130, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(lblLoggain)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEpost)
                        .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLosenord)
                        .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addComponent(btnLoggain)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggainActionPerformed

        //Denna if-sats kollar om fälten Lösenord och Epost inte är tomt mha klassen validering.
        //Sedan kollar denna metoden om lösenordet och email hör ihopp, om den gör det loggar man in på Agent.
        if(Validering.txtFaltArInteTom(txtLosenord) && Validering.losenordRattLangd(txtLosenord) && Validering.txtFaltArInteTom(txtEpost)){
            try{
                String epost = txtEpost.getText();
                String losenord = txtLosenord.getText();
                String epostOchLosenord = epost + losenord;
                String fragaStatus = "SELECT Administrator from Agent WHERE Epost = '"+ epost +"'";
                String fragaAdministrator = "SELECT Epost, Losenord, Agent_ID FROM Agent";
                String adminStatus = idb.fetchSingle(fragaStatus);
                
                
                ArrayList<HashMap<String, String>> Administrator = idb.fetchRows(fragaAdministrator);
                if ("J".equals(adminStatus)){
                for(int i= 0 ; i<Administrator.size() ; i++){
                    String output = "";
                    output += Administrator.get(i).get("Epost") + Administrator.get(i).get("Losenord");

                    if (epostOchLosenord.equals(output)){
                        JOptionPane.showMessageDialog(null, " Rätt lösnenord angivet" );

                        //Kommer in i Source för Administratör.
                        Administrator adminFonster = new Administrator(idb);
                        adminFonster.setVisible(true);

                        lyckadInloggning = true;
                        break;
                    }
                }
                if (!lyckadInloggning) {
                    JOptionPane.showMessageDialog(null, " Fel epost eller lösenord" );
                    txtLosenord.requestFocus();
                }
                }
                else {
                  JOptionPane.showMessageDialog(null, " Adminstatus saknas för den angivna mejlen och lösenordet" );
                    txtLosenord.requestFocus();     
                }

            }catch(InfException ettUndantag){

                JOptionPane.showMessageDialog(null, " Databasfel" );
                System.out.println("Internt felmedelande" + ettUndantag.getMessage());
                txtLosenord.requestFocus();

            }
        }
            
             
    }//GEN-LAST:event_btnLoggainActionPerformed

    private javax.swing.JButton btnLoggain;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLoggain;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtLosenord; 
    
}      
        
        
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminInloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminInloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminInloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminInloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               // new AdminInloggning().setVisible(true);
//            }
//        });
//    }

/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggain;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLoggain;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtLosenord;
    // End of variables declaration//GEN-END:variables
*/

