/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.sql.Statement;


public class Agent extends javax.swing.JFrame {

    //Fälten för klassen Agent
    private InfDB idb;
    private String Agent_ID;
    private String Namn;
    private String Telefon;
    private String Anstallningsdatum;
    private String Administrator;
    private String Epost;
    private String Losenord;
    //private int (främmande nyckel) Omrade;
    
    
    //Konstruktor för Agent klassen
    public Agent(InfDB db, String Agent_ID) { 
        
        idb = db;
        this.Agent_ID= Agent_ID;
       // this.Namn = Namn;
       //this.Telefon = Telefon;
       // this.Anstallningsdatum = Anstallningsdatum;
       // this.Administrator = Administrator;
       // this.Epost = Epost;
       //this.Losenord = Losenord;
        
        
        initComponents();
    }
    
    //Get + set för övriga fields in 
    public String getAgen_ID() {
        return Agent_ID;
    }
    
    public void setAgent_ID(int Agent_ID) {
        this.Agent_ID = Agent_ID;
    }
    
    public String getNamn() {
        return Namn;
    }
    
    public void setNamn(String Namn) {
        this.Namn = Namn;
    }
    
    public String getTelefon() {
        return Telefon;
    }
    
    public void setTelefon(String Telefon) {
        this.Telefon = Telefon;
    }
    
    public String getAnstallningsdatum() {
        return Anstallningsdatum;
    }
    
    public void setAnstallningsdatum(String Anstallningsdatum) {
        this.Anstallningsdatum = Anstallningsdatum;
    }
    
    public String getAdministrator() {
        return Administrator;
    }
    
    public void setAdministrator(String Administrator) {
        this.Administrator = Administrator;
    }
    
    public String getEpost() {
        return Epost;
    }
    
    public void setEpost(String Epost) {
        this.Epost = Epost;
    }
     public String getLosenord() {
        return Losenord;
     }
    
    
    //Här ska get + set kanske in om vi ska ha område som fält
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStartsidaAgent = new javax.swing.JLabel();
        btbAndraLosenordAgent = new javax.swing.JButton();
        lblOmradeschefAgent = new javax.swing.JLabel();
        txtOmradeschefAgent = new javax.swing.JTextField();
        lblKontorschefAgent = new javax.swing.JLabel();
        txtgammaltLosenord = new javax.swing.JTextField();
        txtKontorschefAgent = new javax.swing.JTextField();
        lblgammaltLosenord = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        txtEpost = new javax.swing.JTextField();
        lblNyttLosenord = new javax.swing.JLabel();
        txtNyttLosenord = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStartsidaAgent.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        lblStartsidaAgent.setText("Startsida AGENT");

        btbAndraLosenordAgent.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        btbAndraLosenordAgent.setText("Ändra Lösenord");
        btbAndraLosenordAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAndraLosenordAgentActionPerformed(evt);
            }
        });

        lblOmradeschefAgent.setFont(new java.awt.Font("Big Caslon", 0, 13)); // NOI18N
        lblOmradeschefAgent.setText("Områdenschef");

        txtOmradeschefAgent.setColumns(4);
        txtOmradeschefAgent.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N

        lblKontorschefAgent.setFont(new java.awt.Font("Big Caslon", 0, 13)); // NOI18N
        lblKontorschefAgent.setText("Kontorschef");

        txtKontorschefAgent.setColumns(4);

        lblgammaltLosenord.setText("Gammalt Lösenord");

        lblEpost.setText("Epost");

        lblNyttLosenord.setText("Nytt Lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStartsidaAgent)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOmradeschefAgent)
                                    .addComponent(lblKontorschefAgent))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOmradeschefAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKontorschefAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btbAndraLosenordAgent)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblgammaltLosenord)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblEpost))
                                    .addComponent(lblNyttLosenord))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgammaltLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblStartsidaAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOmradeschefAgent)
                    .addComponent(txtOmradeschefAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontorschefAgent)
                    .addComponent(txtKontorschefAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgammaltLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgammaltLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyttLosenord)
                    .addComponent(txtNyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btbAndraLosenordAgent)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Tagit bort email och nu har vi bara att skriva in gammalt lösenord och nytt lösenord som text fields. 
    //Metdoen jämför om det gamla lösenordet är korrekt, och om det är det så ändras värdet på lösonordsfältet till det man skrev in. 
    //Annars kommmer det ett felmedelande.
    
    private void btbAndraLosenordAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAndraLosenordAgentActionPerformed
    try
      {
              //String inskrivenEpost = txtEpost.getText();
              String gammaltLosenord = txtgammaltLosenord.getText(); 
              String nyttLosenord = txtNyttLosenord.getText();
	      String fragaAgent = "SELECT Epost, Losenord FROM Agent";

              ArrayList<HashMap<String, String>> Agent = idb.fetchRows(fragaAgent);
         
                for(int i = 0; i<Agent.size() ; i++){
                       ArrayList<HashMap<String, String>> enAgent = enAgent.get(i);
                        
                             if(gammaltLosenord)= enAgent.getLosenord()){
              
                                 Losenord = nyttLosenord;
                          }
                       }
             }catch(NumberFormatException e){
           
           JOptionPane.showMessageDialog(null, " Fel lösnenord angivet" );
            txtgammaltLosenord.requestFocus();
           
        }
    }//GEN-LAST:event_btbAndraLosenordAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAndraLosenordAgent;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblKontorschefAgent;
    private javax.swing.JLabel lblNyttLosenord;
    private javax.swing.JLabel lblOmradeschefAgent;
    private javax.swing.JLabel lblStartsidaAgent;
    private javax.swing.JLabel lblgammaltLosenord;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtKontorschefAgent;
    private javax.swing.JTextField txtNyttLosenord;
    private javax.swing.JTextField txtOmradeschefAgent;
    private javax.swing.JTextField txtgammaltLosenord;
    // End of variables declaration//GEN-END:variables
}
