/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author oliviacleve
 */
public class Alien extends javax.swing.JFrame {

    private InfDB idb;
    private int Alien_ID;
    private String Registreringsdatum;
    private String Epost;
    private String Losenord;
    private String Namn;
    private int Telefon;
    //private int Plats;
    //private int Ansvarig_Agent;
    
    /**
     * Creates new form Alien
     */
    //test
    public Alien(InfDB db, int Alien_ID) {
        idb = db;
        this.Alien_ID = Alien_ID;
        this.Registreringsdatum = Registreringsdatum;
        this.Epost = Epost;
        this.Losenord = Losenord;
        this.Namn = Namn;
        this.Telefon = Telefon;
        initComponents();
    }
    
    public int getAlien_ID() {
        return Alien_ID;
    }
    
    public void setAlien_ID() {
        this.Alien_ID = Alien_ID;
    }
    
    public String getRegistreringsdatum() {
        return Registreringsdatum;
    }
    
    //public void setRegistreringsdatum() {
    //  this.Registreringsdatum = Registreringsdatum;
    //}
    
    
    public String getEpost() {
        return Epost;
    }
    
    public void setEpost() {
        this.Epost = Epost;
    }
    
    public String getLosenord() {
        return Losenord;
    }
    
    public void setLosenord() {
        this.Losenord = Losenord;
    }
    
    public String getNamn() {
        return Namn;
    }
    
    public void setNamn() {
        this.Namn = Namn;
    }
    
    public int getTelefon() {
        return Telefon;
    }
    
    public void setTelefon() {
        this.Telefon = Telefon;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStartsidaAlien = new javax.swing.JLabel();
        btnAndraLosenordAlien = new javax.swing.JButton();
        txtOmradeschefAlien = new javax.swing.JTextField();
        lblOmradeschefAlien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStartsidaAlien.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        lblStartsidaAlien.setText("Startsida ALIEN");

        btnAndraLosenordAlien.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        btnAndraLosenordAlien.setText("Ändra Lösenord");

        txtOmradeschefAlien.setColumns(4);

        lblOmradeschefAlien.setFont(new java.awt.Font("Big Caslon", 0, 13)); // NOI18N
        lblOmradeschefAlien.setText("Områdeschef");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOmradeschefAlien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOmradeschefAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAndraLosenordAlien)
                    .addComponent(lblStartsidaAlien))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblStartsidaAlien)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOmradeschefAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOmradeschefAlien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(btnAndraLosenordAlien)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosenordAlien;
    private javax.swing.JLabel lblOmradeschefAlien;
    private javax.swing.JLabel lblStartsidaAlien;
    private javax.swing.JTextField txtOmradeschefAlien;
    // End of variables declaration//GEN-END:variables
}
