/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;


/**
 *
 * @author oliviacleve
 */
public class Minutrustning extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form Minutrustning
     */
    public Minutrustning(InfDB db) {
        idb = db;
        initComponents();
        fylltxtAreaUtkvitteradutrustning();
    }
    
      private void fylltxtAreaUtkvitteradutrustning()
    {
         txtAreaUtkvitteradutrustning.setText("");
    
        ArrayList<HashMap<String, String>> Utkvittutrust = new ArrayList<HashMap<String, String>>();
        
        try {
            String fraga = "SELECT Utrustnings_ID, Benamning FROM Utrustning WHERE Utrustnings_ID IN (SELECT Utrustnings_ID FROM Innehar_Utrustning WHERE Agent_ID IN (SELECT Agent_ID FROM Agent))";
            Utkvittutrust = idb.fetchRows(fraga);
            
            for (HashMap<String, String> Utrust : Utkvittutrust) {
                txtAreaUtkvitteradutrustning.append(Utrust.get("Utrustnings_ID") + "\t");
                txtAreaUtkvitteradutrustning.append(Utrust.get("Benamning") + "\n");
            }
        } catch (InfException UndantagEn) {
                    JOptionPane.showMessageDialog(null, "Databasfel!");
                    System.out.println("Internt felmeddelande" + UndantagEn.getMessage());
                }
                catch (Exception UndantagEn) {
                    JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
                    System.out.println("Internt felmeddelande" + UndantagEn.getMessage());
                }
        
  
        }
      
      // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cbVäljkategori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKategoriförutkvitteradutrustning;
    private javax.swing.JLabel lblUtkvittrubrik;
    private javax.swing.JTextArea txtAreaUtkvitteradutrustning;
    // End of variables declaration  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUtkvittrubrik = new javax.swing.JLabel();
        cbVäljkategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaUtkvitteradutrustning = new javax.swing.JTextArea();
        lblKategoriförutkvitteradutrustning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUtkvittrubrik.setFont(new java.awt.Font("Beirut", 0, 13)); // NOI18N
        lblUtkvittrubrik.setText("Här visas den utrustning du har utkvitterad:");

        cbVäljkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtAreaUtkvitteradutrustning.setColumns(20);
        txtAreaUtkvitteradutrustning.setRows(5);
        txtAreaUtkvitteradutrustning.setText("Man vill ju kunna visa ifall en agent har flera vapen utkvitterade samtidigt.\nSka vi då ha en combobox eller hur gör vi?");
        jScrollPane1.setViewportView(txtAreaUtkvitteradutrustning);

        lblKategoriförutkvitteradutrustning.setText("Välj kategori");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUtkvittrubrik)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKategoriförutkvitteradutrustning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbVäljkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUtkvittrubrik)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategoriförutkvitteradutrustning)
                    .addComponent(cbVäljkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Minutrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Minutrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Minutrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Minutrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               // new Minutrustning().setVisible(true);
//            }
//        });
//    }

    /*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbVäljkategori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKategoriförutkvitteradutrustning;
    private javax.swing.JLabel lblUtkvittrubrik;
    private javax.swing.JTextArea txtAreaUtkvitteradutrustning;
    // End of variables declaration//GEN-END:variables
*/
}
