/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author sarahill
 */
public class TabBortUtrustning extends javax.swing.JFrame {

    /**
     * Konstruktor för TabBortUtrustning
     */
    private InfDB idb;
    
    public TabBortUtrustning(InfDB db) {
        idb = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUtrustningsID = new javax.swing.JTextField();
        btnraderaUtrustning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel1.setText("Skriv in ett Utrustnings-ID för att radera från systemet. Det går inte att ångra denna åtgärd.");

        txtUtrustningsID.setColumns(7);

        btnraderaUtrustning.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnraderaUtrustning.setText("Radera");
        btnraderaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraderaUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnraderaUtrustning)
                    .addComponent(txtUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnraderaUtrustning)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnraderaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraderaUtrustningActionPerformed
   //Raderar en utrustning från systemet
        try{
            //Ger variabelnman till värdena från rutorna och boxarna
            String utrustningsID = txtUtrustningsID.getText();
            String raderaFraga = "SELECT Utrustnings_ID from mibdb.Utrustning";
            
            //Hämtar kolumnen enligt sql-frågan och gör en lista
            ArrayList allaUtrustningsID = idb.fetchColumn(raderaFraga);
            
            //Kollar om ID:t finns i listan
            if (allaUtrustningsID.contains(utrustningsID)){
            //Uppdaterar databasen
            String raderaUtrustningInnehar = "DELETE FROM Innehar_Utrustning WHERE Utrustnings_ID = " + utrustningsID ;
            idb.delete(raderaUtrustningInnehar);
            
            String raderaUtrustningKommunikation = "DELETE FROM Kommunikation WHERE Utrustnings_ID = " + utrustningsID;
            idb.delete(raderaUtrustningKommunikation);
            
            String raderaUtrustningTeknik = "DELETE FROM Teknik WHERE Utrustnings_ID = " + utrustningsID;
            idb.delete(raderaUtrustningTeknik);
            
            String raderaUtrustningVapen = "DELETE FROM Vapen WHERE Utrustnings_ID = " + utrustningsID;
            idb.delete(raderaUtrustningVapen);
            
            String raderaUtrustning = "DELETE FROM Utrustning WHERE Utrustnings_ID = " + utrustningsID;
            idb.delete(raderaUtrustning);


            //Skriver ut meddelande att agenten är raderad
            JOptionPane.showMessageDialog(null, " Utrustningen har raderats." );
            }
            else { JOptionPane.showMessageDialog(null, " Utrustningen hittades inte." );
                
            }
        }
        catch (InfException ettUndantag){
            
              JOptionPane.showMessageDialog(null, " Databasfel" );
              System.out.println("Det gick inte att ta bort utrustningen" + ettUndantag.getMessage());
              //txtraderaAlien.requestFocus();
        }
}
    private javax.swing.JButton btnraderaUtrustning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtUtrustningsID;
    }//GEN-LAST:event_btnraderaUtrustningActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TabBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TabBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TabBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TabBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new TabBortUtrustning().setVisible(true);
//            }
//        });
//    }
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnraderaUtrustning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtUtrustningsID;
    // End of variables declaration//GEN-END:variables
}*/
