/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author sarahill
 */
public class TaBortAlien extends javax.swing.JFrame {

    /**
     * Creates new form TaBortAlien
     */
    
    private InfDB idb;
    
    public TaBortAlien(InfDB db) {
        idb=db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAlienIDRadera = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRaderaAlien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAlienIDRadera.setColumns(7);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel1.setText("Skriv in Alien-ID på den alien du vill radera från systemet. Det går inte att ångra denna åtgärd.");

        btnRaderaAlien.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnRaderaAlien.setText("Radera");
        btnRaderaAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaAlienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRaderaAlien)
                    .addComponent(txtAlienIDRadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlienIDRadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnRaderaAlien)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaderaAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaAlienActionPerformed
        //Raderar en alien från systemet
               try{
            //Ger variabelnman till värdena från rutorna och boxarna
            String alienID = txtAlienIDRadera.getText();
            String raderaFraga = "SELECT alien_ID from mibdb.Alien";
            
            //Hämtar kolumnen enligt sql-frågan och gör en lista
            ArrayList allaAlienID = idb.fetchColumn(raderaFraga);
            
            //Kollar om ID:t finns i listan
            if (allaAlienID.contains(alienID)){
            //Uppdaterar databasen
            String raderaAlienBoglodite = "DELETE FROM Boglodite WHERE Alien_ID = " + alienID;
            idb.delete(raderaAlienBoglodite);
            
            String raderaAlienSquid = "DELETE FROM Omradeschef WHERE Alien_ID = " + alienID;
            idb.delete(raderaAlienSquid);
            
            String raderaAlienWorm = "DELETE FROM Omradeschef WHERE Alien_ID = " + alienID;
            idb.delete(raderaAlienWorm);
            
            String raderaAlien = "DELETE FROM Alien WHERE Alien_ID = " + alienID;
            idb.delete(raderaAlien);

            //Skriver ut meddelande att agenten är raderad
            JOptionPane.showMessageDialog(null, " Alien har raderats." );
            }
            else { JOptionPane.showMessageDialog(null, " Alien hittades inte." );
                
            }
        }
        catch (InfException ettUndantag){
            
              JOptionPane.showMessageDialog(null, " Databasfel" );
              System.out.println("Det gick inte att ta bort alien" + ettUndantag.getMessage());
              //txtraderaAlien.requestFocus();
        }
     

}
    private javax.swing.JButton btnRaderaAlien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAlienIDRadera;
        
    }//GEN-LAST:event_btnRaderaAlienActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TaBortAlien().setVisible(true);
//            }
//        });
//    }
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaderaAlien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAlienIDRadera;
    // End of variables declaration//GEN-END:variables
}*/
